import type { StudentRecord } from './recordUtils';
import type { VerificationStatus } from './verificationTypes';

// ── Mock records for demo mode ─────────────────────────────────────────────

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
};

export const DEMO_STUDENT_RECORDS: StudentRecord[] = [
  {
    id: 'demo-1',
    title: 'AWS Cloud Practitioner Certification',
    category: 'Certifications',
    description: 'Completed the AWS Cloud Practitioner certification, covering cloud concepts, security, billing, and core AWS services.',
    date: daysAgo(15),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(15),
    verification_status: 'auto_verified' as VerificationStatus,
    verification_confidence: 94,
    verification_notes: 'Valid AWS certificate detected · Matches: ✓ Name, ✓ Date, ✓ Category, ✓ Title · Issuer: Amazon Web Services · Type: certificate · Confidence: 94%',
    verified_at: daysAgo(15),
    institution_name: 'Amazon Web Services',
    engagement_points: 15,
  },
  {
    id: 'demo-2',
    title: 'Smart India Hackathon 2024 — Finalist',
    category: 'Competitions',
    description: 'Reached the national finals of SIH 2024 with a team project on AI-powered student credential verification.',
    date: daysAgo(30),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(30),
    verification_status: 'auto_verified' as VerificationStatus,
    verification_confidence: 91,
    verification_notes: 'Official SIH finalist certificate · Matches: ✓ Name, ✓ Date, ✓ Category, ✓ Title · Issuer: AICTE · Type: certificate · Confidence: 91%',
    verified_at: daysAgo(29),
    institution_name: 'AICTE / MoE',
    engagement_points: 20,
  },
  {
    id: 'demo-3',
    title: 'React & TypeScript Workshop',
    category: 'Conferences & Workshops',
    description: 'Attended a 2-day hands-on workshop on building production React apps with TypeScript, Vite, and Tailwind CSS.',
    date: daysAgo(45),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(45),
    verification_status: 'needs_review' as VerificationStatus,
    verification_confidence: 68,
    verification_notes: 'Screenshot of participation · Matches: ✓ Name, ? Date, ✓ Category, ✓ Title · Issuer: DevCommunity · Type: screenshot · Confidence: 68%',
    verified_at: daysAgo(44),
    institution_name: 'Presidency University',
    engagement_points: 10,
  },
  {
    id: 'demo-4',
    title: 'NSS Volunteer — Blood Donation Drive',
    category: 'Community Service',
    description: 'Organized and participated in the annual blood donation drive conducted by the NSS unit, serving 200+ donors.',
    date: daysAgo(60),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(60),
    verification_status: 'manual_verified' as VerificationStatus,
    verification_confidence: null,
    verification_notes: 'Manually verified by a teacher.',
    verified_at: daysAgo(58),
    verified_by: 'demo-teacher',
    institution_name: 'NSS Unit, Presidency University',
    engagement_points: 12,
  },
  {
    id: 'demo-5',
    title: 'Frontend Development Internship at Infosys',
    category: 'Internships',
    description: '8-week summer internship building internal dashboards with React and Node.js at Infosys Bangalore.',
    date: daysAgo(90),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(90),
    verification_status: 'auto_verified' as VerificationStatus,
    verification_confidence: 88,
    verification_notes: 'Internship offer letter detected · Matches: ✓ Name, ✓ Date, ✓ Category, ✓ Title · Issuer: Infosys Ltd · Type: letter · Confidence: 88%',
    verified_at: daysAgo(89),
    institution_name: 'Infosys Ltd',
    engagement_points: 18,
  },
  {
    id: 'demo-6',
    title: 'Dean\'s List — Semester 5',
    category: 'Academic Excellence',
    description: 'Secured position on the Dean\'s Merit List with a CGPA of 9.2 for Semester 5.',
    date: daysAgo(120),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(120),
    verification_status: 'auto_verified' as VerificationStatus,
    verification_confidence: 96,
    verification_notes: 'Official university transcript · Matches: ✓ Name, ✓ Date, ✓ Category, ✓ Title · Issuer: Presidency University · Type: transcript · Confidence: 96%',
    verified_at: daysAgo(119),
    institution_name: 'Presidency University',
    engagement_points: 15,
  },
  {
    id: 'demo-7',
    title: 'Technical Lead — Google Developer Student Club',
    category: 'Leadership Roles',
    description: 'Served as Technical Lead for GDSC, organizing 12+ coding workshops and mentoring 50+ students.',
    date: daysAgo(150),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(150),
    verification_status: 'auto_verified' as VerificationStatus,
    verification_confidence: 85,
    verification_notes: 'GDSC appointment letter · Matches: ✓ Name, ✓ Date, ✓ Category, ✓ Title · Issuer: Google · Type: letter · Confidence: 85%',
    verified_at: daysAgo(149),
    institution_name: 'Google',
    engagement_points: 16,
  },
  {
    id: 'demo-8',
    title: 'Photography Club — Core Member',
    category: 'Club Activities',
    description: 'Active core member of the Photography Club, contributed to annual exhibitions and mentored juniors.',
    date: daysAgo(200),
    image_url: null,
    user_id: 'demo-student',
    created_at: daysAgo(200),
    verification_status: 'rejected' as VerificationStatus,
    verification_confidence: 32,
    verification_notes: 'Image appears to be an unrelated personal photo · Matches: ✗ Name, ✗ Date, ✗ Category, ✗ Title · Issuer: null · Type: photo · Confidence: 32%',
    verified_at: daysAgo(199),
    institution_name: 'Presidency University',
    engagement_points: 5,
  },
];

// For teacher/admin views — add student profile info
export const DEMO_TEACHER_RECORDS = DEMO_STUDENT_RECORDS.map((r) => ({
  ...r,
  profiles: {
    full_name: 'Priya Sharma',
    avatar_url: null,
    role: 'student' as const,
  },
}));
